### ISSUE TITLE
Sequence Increment by two

### ISSUE THREAD

**Issue by billbonney** [dogmaphobic/mavesp8266#4]
I read the code line below comment
https://github.com/dogmaphobic/mavesp8266/blob/master/src/main.cpp#L423
The reason QGC increments the seq by 2 is that it first packs a message (which calls finalize) and then sends the message later calling finalize again, doing another increment of the seq id.

and I now just read the comment here
https://github.com/dogmaphobic/mavesp8266/blob/master/src/main.cpp#L764

Some command use _send directly so the increment would be the expected 1 in that case.

**Comment by dogmaphobic** [comment]
I heard yesterday on the call :) I posted an issue here:

https://github.com/mavlink/qgroundcontrol/issues/2627

**Comment by dogmaphobic** [comment]
Done! :)
