### ISSUE TITLE
Multiple UAVs over WiFi?

### ISSUE THREAD

**Issue by jonathanrutherford** [dogmaphobic/mavesp8266#42]
Hi guys, thanks for your awesome work!
I'm trying to connect a couple of pixracer drones to qgroundcontrol to test RTK, is there any way to set up the esp8266 so I can see both? I've tried to set them up as STA's but I can't connect to them from qgc like this. Any clues?
Again, many thanks for your great effort,

Jono

**Comment by dogmaphobic** [comment]
These questions are better asked here: https://gitter.im/dogmaphobic/mavesp8266

If you want to set them up in *Station* mode, you will need an AP somewhere (a Wi-Fi router) so all nodes involved can connect to, including QGC. That way, they are all part of the same network.

**Comment by jonathanrutherford** [comment]
Ok, thanks.
