### ISSUE TITLE
cannot use at APM2.6 board

### ISSUE THREAD

**Issue by uKingSky** [dogmaphobic/mavesp8266#46]
HI,all,
i use mavesp8266 code at pixhawk board,it can connect sucessfully, but when i use at APM2.6 board, it cannot connect .could you tell me why?

**Comment by davidbuzz** [comment]
apm2.6 hardware is so very very old, and this is unlikely to be fixed. I recommend throwing your APM hardware in the trashcan.

**Comment by a66as** [comment]
I did that, Purchased a new board with a 3DR telemetry.
