### ISSUE TITLE
RTSP from GoPro via ESP8266?

### ISSUE THREAD

**Issue by ziemowitp** [dogmaphobic/mavesp8266#49]
Gopro and others have live streaming available via RTSP when connecting via WIFI.  Doesn't ESP8266 support running both STA and AP at the same time?  Connecting to both ESP8266 (AP) and GoPro via ESP8266 (STA) to get both MAVLINK and video would be nice!

**Comment by dogmaphobic** [comment]
Even if it did, there is nowhere near enough bandwidth for an RTSP stream.
